### ISSUE TITLE
TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by oceanlazy** [kivy-garden/garden.roulette#6]
After `python __init__.py`
```
[INFO   ] [Logger      ] Record log in /home/v/.kivy/logs/kivy_19-01-31_54.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'SVGA3D; build: RELEASE;  LLVM;'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/home/v/PycharmProjects/test/test3.py", line 476, in <module>
     b.add_widget(Roulette(density=2.8, selected_value=2013))
   File "/home/v/PycharmProjects/test/test3.py", line 336, in __init__
     super(Roulette, self).__init__(**kw)
   File "/home/v/.kivy/garden/garden.tickline/__init__.py", line 568, in __init__
     self.on_scroll_effect_cls()
   File "/home/v/.kivy/garden/garden.tickline/__init__.py", line 614, in on_scroll_effect_cls
     effect = self.scroll_effect = self.scroll_effect_cls(round_value=False)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/effects/kinetic.py", line 110, in __init__
     super(KineticEffect, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes no parameters
```

**Comment by fherbine** [comment]
I did that https://github.com/kivy-garden/garden.tickline/issues/8
